import React, { Component } from "react";
import ImageMap from "../../src/RoadXperience.jpg";
import ImageMapper from "react-image-mapper";
import { withAuthConsumer } from "../contexts/AuthStore";
import LayoutApp from "./misc/LayoutApp";
import { Redirect } from "react-router-dom";

// Image Map Generated by http://www.image-map.net/
const MAP = {
  name: "image-map",
  areas: [
    {
      name: "Busco",
      shape: "rect",
      coords: [2393, 2270, 1872, 2164],
      preFillColor: "red"
    },
    {
      name: "Reservo",
      shape: "rect",
      coords: [1824, 1956, 2324, 1850],
      preFillColor: "black"
    },
    {
      name: "Preparo",
      shape: "rect",
      coords: [1426, 1717, 1947, 1611],
      preFillColor: "white"
    },
    {
      name: "Disfruto",
      shape: "rect",
      coords: [1318, 1470, 1839, 1364],
      preFillColor: "blue"
    },
    {
      name: "Recuerdo",
      shape: "rect",
      coords: [1545, 1125, 2066, 1019],
      preFillColor: "yellow"
    }
  ]
};

class Road extends Component {
// const Road = () => {

  state = {
    hoveredArea: null,
     msg: null,
     moveMsg: null,
     areaName: ''
   };

  load() {
    this.setState({ msg: 'Interact with image !' });
    // console.log(this.state.msg);
	}
	clicked(area) {
    this.setState({ msg: `You clicked on ${area.shape} at coords ${JSON.stringify(area.coords)} !`});
    // console.log(this.state.msg);
	}
	clickedOutside(evt) {
		const coords = {x: evt.nativeEvent.layerX, y: evt.nativeEvent.layerY };
    this.setState({ msg: `You clicked on the image at coords ${JSON.stringify(coords)} !` });
    // console.log(this.state.msg);
	}
	moveOnImage(evt) {
		const coords = {x: evt.nativeEvent.layerX, y: evt.nativeEvent.layerY };
    this.setState({ moveMsg: `You moved on the image at coords ${JSON.stringify(coords)} !` });
    // console.log(this.state.moveMsg);
	}
	enterArea(area) {
    console.log(area);
    this.setState({ hoveredArea: area, msg: `You entered ${area.shape} ${area.name} at coords ${JSON.stringify(area.coords)} !`, areaName: area.name });
    console.log(`Entrando en: ${area.name}`);
	}
	getTipPosition(area) {
		return { top: `${area.center[1]}px`, left: `${area.center[0]}px` };
	}

  render () {  
    const { areaName } = this.state;

    if (areaName !== '') {
      switch (areaName) {
        case 'Busco':
          return <Redirect to="/busco" />;
        case 'Reservo':
          return <Redirect to="/reservo" />;
        case 'Preparo':
          return <Redirect to="/preparo" />;
        case 'Disfruto':
          return <Redirect to="/disfruto" />;
        case 'Recuerdo':
          return <Redirect to="/recuerdo" />;
        default:
          return <Redirect to="/busco" />;
      }
    }

    // if (areaName === 'Busco') {
    //   return <Redirect to="/busco" />;
    // }
    // else if (areaName !== '') {
    //   return <Redirect to="/profile" />;
    // }
    
    return (
      <LayoutApp>
            <div style={{ display: 'flex', justifyContent: 'center', marginTop: '10vh' }} >
        <ImageMapper
          src={ImageMap}
          map={MAP}
          imgWidth={2800}
          width={450}
          onLoad={() => this.load()}
  							onClick={area => this.clicked(area)}
  							onMouseEnter={area => this.enterArea(area)}
  							onImageClick={evt => this.clickedOutside(evt)}
  							onImageMouseMove={evt => this.moveOnImage(evt)}
        />
        {
  							this.state.hoveredArea &&
  							<span className="tooltip" style={{ ...this.getTipPosition(this.state.hoveredArea)}}>
  								{ this.state.hoveredArea && this.state.hoveredArea.name}
  							</span>
  						}

        </div>
      </LayoutApp>
    );
  }
};

export default withAuthConsumer(Road);
